### ISSUE TITLE
I just want to point out an issue in your shell script.

### ISSUE THREAD

**Issue by ghost** [fallc0nn/xdg-dmenu#2]
Hello, I have just figured out that the code doesn't work perfectly as expected. 

The issue is that every time when one tries to select items in a submenu, it will only work if the selected item is of type submenu instead of app ( ".desktop files I suppose ") . 

Regarding this issue, I have added this line :
`[[ $submenu_selected == *">"* ]] && submenu_selected="$(echo $submenu_select    ed | grep -Eo "> [^>]+$")"`
right between the lines
`submenu_selected=....`
&
`[[ ! "$submenu_selected" ]] && exit 1`
and the code now works perfectly.

For those wondering why it doesn't work, this is the patch.

**Comment by f4llc0nn** [comment]
Thanks for the heads up. I have no intention to do any maintenance in this code. Feel free to fork and do your own version.
